// <auto-generated />
namespace ERPProject.Persistance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class amountprice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(amountprice));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071917177_amount price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
